baseURL               = "https://dh.moorli.de/"
languageCode          = "zh-CN"
title                 = "moorli导航站--一站式解决方案"
description           = "免费服务器 免费资源 Mjj的导航站 必备工具 导航"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "docs"					# 站点静态文件保存目录


# Robots.txt
enableRobotsTXT = true

[params]
    author        = "AiEDU"
    description   = "免费服务器 免费资源 Mjj的导航站 必备工具 导航"
    upload        = "https://dh.moorli.de"  # 左侧导航栏的"网站提交"
    about         = ""	# 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com/rsgzs"
    enablePreLoad = true					# 网站完全打开前预加载动画
    textPreLoad   = "Moorli"				# 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false					# 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			# 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/default.webp"		# logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = false					# 默认站点为深色(夜间)模式
    yiyan         = false                         		# 默认启用一言服务

#[params.seo]
    # baiduhmid     = '252f9700e4c1ad32c2647eb839ef71e6'		# 百度统计 hm.src 的 ID
    # baiduSiteVer  = 'codeva-cCAOSG8MBO'				# 百度HTML标签验证(baidu-site-verification)
    # tj51laid        = ''                        		# 51.LA 网站统计
    # tj51lack        = ''
   # GoogleAdsClient = 'G-TZZ8ZZD3FR'

[params.qweather]
    key = ""
[params.ads]
    enable = false

[params.images]
    favicon           = "assets/images/a.png"           # 网站图标
    searchImageL      = "https://s3.aiedu.qzz.io/website/bg-dna.jpg"             # 搜索部分浅色背景图
    searchImageD      = "https://s3.aiedu.qzz.io/website/bg-dna-d.jpg"             # 搜索部分深色背景图
    logoExpandLight   = "assets/images/a.png"               # 扩展状态下的浅色 logo
    logoExpandDark    = "assets/images/a.png"               # 扩展状态下的深色 logo
    logoCollapseLight = "assets/images/a.png"           # 收起状态下的浅色 logo
    logoCollapseDark  = "assets/images/a.png"           # 收起状态下的深色 logo

[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '2025 - {year} By [Moorli](https://github.com/rsgzs) | [My 导航] <br/>'
